#!/bin/sh

wmname LG3D &
pgrep -x sxhkd > /dev/null || sxhkd &

# Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

# Bspwm configuration 
border_width='2.5'
window_gap='14.5'
split_ratio='1.4'

bspc config border_width "$border_width"
bspc config window_gap "$window_gap"
bspc config split_ratio "$split_ratio"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a spotify state=fullscreen
bspc rule -a vlc state=fullscreen
bspc rule -a vmware state=fullscreen
bspc rule -a gimp state=fullscreen

# Floating applications
bspc rule -a arandr state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a cutefish-calculator state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a vmware-netcfg state=floating

# Tiled applications
bspc rule -a gnome-disks state=tiled
bspc rule -a xfce4-settings-manager state=tiled

# open applications on specific workspaces
#bspc rule -a Firefox desktop='^1' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
#bspc rule -a Chromium desktop='^1'  follow=on
#bspc rule -a Subl desktop='^2' follow=on
#bspc rule -a Atom desktop='^2' follow=on
bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
#bspc rule -a Thunar desktop='^8' follow=on
#bspc rule -a discord desktop='^9' follow=on
bspc rule -a Pavucontrol desktop='^10' 
bspc rule -a Spotify desktop='^9' follow=on

#Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window

# Wallpaper
feh --bg-fill ~/Pictures/Wallpapers/Random/13.png &
# picom
picom &
# storage
udiskie -t &
# notification
wired &
# polkit
# /usr/bin/lxpolkit &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# keyboard
setxkbmap us -variant altgr-intl &
# polybar
~/.config/polybar/./launch.sh &
~/.config/polybar/scripts/./launch_polybar &
bspc config border_width 0
